#:schema node_modules/wrangler/config-schema.json
name = "remix-ginnan-app"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]
# main = "./worker.ts"
# assets = { directory = "./build/client" }
pages_build_output_dir = "./build/client"
